services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./openapi_docs:/app/openapi_docs
      - ./db_chroma_cache:/app/db_chroma_cache
      - .:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    tty: true  # Allocate a pseudo-TTY